#!/bin/bash

# On se place dans le dossier où se trouve le fichier
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

# Démarrage du GPS et délais d'une minute pour obtenir le signal
sudo gpsd /dev/ttyS0 -F /var/run/gpsd.sock
sleep 60

# Synchronisation au GPS
SYNC_CLOCK=$(grep -Eo '[0-9]{1,10}' param.txt | head -5 | tail -1)
TIME_LAST_SYNC=$(date -d 'now' +%s)
./synchro_clock_to_gps

sleep 10

while [ 1 ]
do
	# Creation de l'emplois du temps
	./generate_schedule
	sleep 2

	# Envois de l'emplois du temps
	./txrx_schedule sender schedule.txt

	# Jouer l'emplois du temps
	./play_schedule

	# Resynchronisation si le délais précisé en paramètre est dépassé
	if [ $((TIME_LAST_SYNC + SYNC_CLOCk)) -lt $(date -d 'now' +%s) ]
	then
		./synchro_clock_to_gps
		TIME_LAST_SYNC=$(date -d 'now' +%s)
	fi
done
