#!/bin/bash

# On se place dans le dossier qui contient le script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

# Creation du fichier d'emplois du temps schedule.txt si il n'existe pas déjà
touch schedule.txt

# Synchronisation au GPS
./synchro_clock_to_gps
TIME_LAST_SYNC=$(date +%s)

while [ 1 ]
do
	# Recevoir l'emploi du temps
	./txrx_schedule receiver
	
	# Jouer l'empoi du temps
	./play_schedule
	
	# Resynchronisation si le délais précisé en paramètre est dépassé
	if [ $((TIME_LAST_SYNC + SYNC_CLOCk)) -lt $(date -d 'now' +%s) ]
	then
		./synchro_clock_to_gps
		TIME_LAST_SYNC=$(date +%s)
	fi
done
